import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable, TextInput, ActivityIndicator, Alert } from 'react-native';
import { auth, createAccount, login, logout, onAuthStateChanged, User } from '../services/firebase';
import { getOrderHistory, getNotifications, getProfile, saveProfile, getSupportTickets, createSupportTicket } from '../services/api';
import { checkAdmin } from '../services/admin';

type Props={onShop:()=>void;onAdmin:()=>void;onSupport?:()=>void;onNotifications?:()=>void};
export default function Account({onShop,onAdmin,onSupport,onNotifications}:Props){
 const [user,setUser]=useState<User|null>(auth.currentUser);const [mode,setMode]=useState<'login'|'signup'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);const [admin,setAdmin]=useState(false);const [orders,setOrders]=useState<any[]>([]);const [notifications,setNotifications]=useState<any[]>([]);const [phone,setPhone]=useState('');const [address,setAddress]=useState('');const [saving,setSaving]=useState(false);const [supportOpen,setSupportOpen]=useState(false);const [supportSubject,setSupportSubject]=useState('');const [supportMessage,setSupportMessage]=useState('');
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);if(!u)setAdmin(false);}),[]);useEffect(()=>{if(user){void loadPrivate();}},[user]);
 async function loadPrivate(){try{const [a,o,n,p]=await Promise.all([checkAdmin(),getOrderHistory(),getNotifications(),getProfile()]);setAdmin(a.isAdmin);setOrders(o);setNotifications(n);setPhone(p.phone);setAddress(p.address);}catch(e){console.warn('Account load:',e);}}
 async function submitAuth(){if(!email.trim()||!password){setMessage('Enter your email and password.');return;}try{setLoading(true);setMessage('');if(mode==='login')await login(email.trim(),password);else await createAccount(email.trim(),password);setPassword('');setMessage('Welcome to STAYUNKNOWN.');}catch(e:any){setMessage(e?.code==='auth/invalid-credential'?'Email or password is incorrect.':e?.message||'Authentication failed.');}finally{setLoading(false);}}
 async function save(){try{setSaving(true);await saveProfile({phone,address});Alert.alert('Saved','Your account details have been updated.');}catch(e:any){Alert.alert('Could not save',e?.message||'Please try again.');}finally{setSaving(false);}}
 async function sendSupport(){if(!supportMessage.trim()){Alert.alert('Message required');return;}try{await createSupportTicket({subject:supportSubject,message:supportMessage});setSupportSubject('');setSupportMessage('');setSupportOpen(false);Alert.alert('Sent','Your support request has been created.');}catch(e:any){Alert.alert('Could not send',e?.message||'Please try again.');}}
 if(!user)return <ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>ACCOUNT</Text><View style={styles.box}><Text style={styles.heading}>{mode==='login'?'SIGN IN':'CREATE ACCOUNT'}</Text><Text style={styles.label}>EMAIL</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor="#555" autoCapitalize="none" keyboardType="email-address"/><Text style={styles.label}>PASSWORD</Text><TextInput style={styles.input} value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#555" secureTextEntry/>{message?<Text style={styles.message}>{message}</Text>:null}<Pressable style={styles.white} onPress={submitAuth} disabled={loading}>{loading?<ActivityIndicator color="#000"/>:<Text style={styles.black}>{mode==='login'?'SIGN IN':'CREATE ACCOUNT'}</Text>}</Pressable><Pressable onPress={()=>{setMode(mode==='login'?'signup':'login');setMessage('');}}><Text style={styles.switch}>{mode==='login'?'CREATE A NEW ACCOUNT':'ALREADY HAVE AN ACCOUNT? SIGN IN'}</Text></Pressable><Pressable style={styles.outline} onPress={onShop}><Text style={styles.outlineText}>CONTINUE AS GUEST</Text></Pressable></View></ScrollView>;
 return <ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>ACCOUNT</Text><Text style={styles.email}>{user.email}</Text>{admin?<Pressable style={styles.adminButton} onPress={onAdmin}><Text style={styles.adminText}>ADMIN DASHBOARD →</Text></Pressable>:null}<Text style={styles.section}>PROFILE</Text><TextInput style={styles.input} value={phone} onChangeText={setPhone} placeholder="Phone" placeholderTextColor="#555" keyboardType="phone-pad"/><TextInput style={[styles.input,styles.multiline]} value={address} onChangeText={setAddress} placeholder="Delivery address" placeholderTextColor="#555" multiline/><Pressable style={styles.white} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#000"/>:<Text style={styles.black}>SAVE PROFILE</Text>}</Pressable><Text style={styles.section}>ORDERS · {orders.length}</Text>{orders.length===0?<Text style={styles.muted}>No orders yet.</Text>:orders.slice(0,5).map(o=><View key={o.id} style={styles.row}><Text style={styles.rowTitle}>{o.orderNumber||o.paymentReference||o.id}</Text><Text style={styles.rowMeta}>{o.deliveryStatus||o.paymentStatus||'PENDING'} · ₦{Number(o.total||0).toLocaleString('en-NG')}</Text></View>)}<Text style={styles.section}>NOTIFICATIONS · {notifications.filter(n=>!n.read).length} UNREAD</Text>{notifications.length===0?<Text style={styles.muted}>No notifications.</Text>:notifications.slice(0,5).map(n=><View key={n.id} style={styles.row}><Text style={styles.rowTitle}>{n.title||'STAYUNKNOWN'}</Text><Text style={styles.rowMeta}>{n.message||''}</Text></View>)}<Text style={styles.section}>ACTIVITY</Text><Pressable style={styles.outline} onPress={onNotifications}><Text style={styles.outlineText}>NOTIFICATIONS →</Text></Pressable><Pressable style={styles.outline} onPress={onSupport}><Text style={styles.outlineText}>SUPPORT CHAT →</Text></Pressable><Text style={styles.section}>SUPPORT</Text>{supportOpen?<View style={styles.box}><TextInput style={styles.input} value={supportSubject} onChangeText={setSupportSubject} placeholder="Subject" placeholderTextColor="#555"/><TextInput style={[styles.input,styles.multiline]} value={supportMessage} onChangeText={setSupportMessage} placeholder="How can we help?" placeholderTextColor="#555" multiline/><Pressable style={styles.white} onPress={sendSupport}><Text style={styles.black}>SEND REQUEST</Text></Pressable></View>:<Pressable style={styles.outline} onPress={()=>setSupportOpen(true)}><Text style={styles.outlineText}>CONTACT SUPPORT</Text></Pressable>}<Pressable style={styles.logout} onPress={()=>logout()}><Text style={styles.logoutText}>LOG OUT</Text></Pressable></ScrollView>
}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:70},title:{color:'#fff',fontSize:38,fontWeight:'900',letterSpacing:1,marginBottom:8},email:{color:'#777',fontSize:13,marginBottom:20},box:{borderWidth:1,borderColor:'#292929',padding:18,marginTop:10},heading:{color:'#fff',fontSize:14,fontWeight:'900',letterSpacing:1,marginBottom:20},label:{color:'#888',fontSize:9,fontWeight:'900',letterSpacing:1,marginBottom:7},input:{backgroundColor:'#151515',borderWidth:1,borderColor:'#333',color:'#fff',padding:14,marginBottom:12},multiline:{minHeight:85,textAlignVertical:'top'},white:{backgroundColor:'#fff',paddingVertical:17,alignItems:'center',marginTop:4},black:{color:'#000',fontSize:10,fontWeight:'900',letterSpacing:1},switch:{color:'#aaa',fontSize:10,fontWeight:'900',letterSpacing:1,textAlign:'center',padding:18},outline:{borderWidth:1,borderColor:'#fff',paddingVertical:16,alignItems:'center',marginTop:10},outlineText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},adminButton:{backgroundColor:'#fff',paddingVertical:16,alignItems:'center',marginBottom:12},adminText:{color:'#000',fontSize:11,fontWeight:'900',letterSpacing:1},section:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:1,marginTop:28,marginBottom:12},muted:{color:'#666',fontSize:12},row:{borderTopWidth:1,borderTopColor:'#222',paddingVertical:13},rowTitle:{color:'#fff',fontSize:12,fontWeight:'900'},rowMeta:{color:'#777',fontSize:11,marginTop:5,lineHeight:17},message:{color:'#aaa',fontSize:11,marginBottom:12},logout:{alignItems:'center',padding:20,marginTop:20},logoutText:{color:'#777',fontSize:10,fontWeight:'900',letterSpacing:1}}
);
