import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable, TextInput, ActivityIndicator, Alert } from 'react-native';
import { auth, createAccount, login, logout, onAuthStateChanged, User } from '../services/firebase';
import { getProfile, saveProfile } from '../services/api';
import { checkAdmin } from '../services/admin';

type Page='menu'|'profile'|'addresses'|'settings'|'about';
type Props={onShop:()=>void;onAdmin:()=>void;onSupport?:()=>void;onNotifications?:()=>void;onOrders?:()=>void;onWishlist?:()=>void};

export default function Account({onShop,onAdmin,onSupport,onNotifications,onOrders,onWishlist}:Props){
 const [user,setUser]=useState<User|null>(auth.currentUser); const [mode,setMode]=useState<'login'|'signup'>('login');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [admin,setAdmin]=useState(false);
 const [page,setPage]=useState<Page>('menu'); const [phone,setPhone]=useState(''); const [address,setAddress]=useState(''); const [saving,setSaving]=useState(false); const [profileLoading,setProfileLoading]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u); if(!u){setAdmin(false);setPage('menu');}}),[]);
 useEffect(()=>{if(user) void loadProfile();},[user]);
 async function loadProfile(){try{setProfileLoading(true);const [p,a]=await Promise.all([getProfile(),checkAdmin()]);setPhone(p.phone||'');setAddress(p.address||'');setAdmin(a.isAdmin);}catch(e){console.warn('Account load:',e);}finally{setProfileLoading(false);}}
 async function submitAuth(){if(!email.trim()||!password){setMessage('Enter your email and password.');return;}try{setLoading(true);setMessage('');if(mode==='login')await login(email.trim(),password);else await createAccount(email.trim(),password);setPassword('');setMessage('Welcome to STAYUNKNOWN.');}catch(e:any){setMessage(e?.code==='auth/invalid-credential'?'Email or password is incorrect.':e?.message||'Authentication failed.');}finally{setLoading(false);}}
 async function save(){try{setSaving(true);await saveProfile({phone,address});Alert.alert('Saved','Your account details have been updated.');}catch(e:any){Alert.alert('Could not save',e?.message||'Please try again.');}finally{setSaving(false);}}
 if(!user)return <ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>ACCOUNT</Text><View style={styles.box}><Text style={styles.heading}>{mode==='login'?'SIGN IN':'CREATE ACCOUNT'}</Text><Text style={styles.label}>EMAIL</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor="#555" autoCapitalize="none" keyboardType="email-address"/><Text style={styles.label}>PASSWORD</Text><TextInput style={styles.input} value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#555" secureTextEntry/>{message?<Text style={styles.message}>{message}</Text>:null}<Pressable style={styles.white} onPress={submitAuth} disabled={loading}>{loading?<ActivityIndicator color="#000"/>:<Text style={styles.black}>{mode==='login'?'SIGN IN':'CREATE ACCOUNT'}</Text>}</Pressable><Pressable onPress={()=>{setMode(mode==='login'?'signup':'login');setMessage('');}}><Text style={styles.switch}>{mode==='login'?'CREATE A NEW ACCOUNT':'ALREADY HAVE AN ACCOUNT? SIGN IN'}</Text></Pressable><Pressable style={styles.outline} onPress={onShop}><Text style={styles.outlineText}>CONTINUE AS GUEST</Text></Pressable></View></ScrollView>;
 if(page==='profile') return <PageShell title="PERSONAL INFORMATION" onBack={()=>setPage('menu')}><Text style={styles.label}>EMAIL</Text><View style={styles.readonly}><Text style={styles.readonlyText}>{user.email||'—'}</Text></View><Text style={styles.label}>PHONE</Text><TextInput style={styles.input} value={phone} onChangeText={setPhone} placeholder="Phone" placeholderTextColor="#555" keyboardType="phone-pad"/><Pressable style={styles.white} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#000"/>:<Text style={styles.black}>SAVE CHANGES</Text>}</Pressable></PageShell>;
 if(page==='addresses') return <PageShell title="DELIVERY ADDRESSES" onBack={()=>setPage('menu')}>{profileLoading?<ActivityIndicator color="#fff"/>:<><Text style={styles.label}>DEFAULT ADDRESS</Text><TextInput style={[styles.input,styles.multiline]} value={address} onChangeText={setAddress} placeholder="Delivery address" placeholderTextColor="#555" multiline/><Pressable style={styles.white} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#000"/>:<Text style={styles.black}>SAVE ADDRESS</Text>}</Pressable><Text style={styles.muted}>Your default delivery address is used during checkout. You can change it at any time.</Text></>}</PageShell>;
 if(page==='settings') return <PageShell title="SETTINGS" onBack={()=>setPage('menu')}><SettingRow title="Email notifications" subtitle="Receive important account and order updates"/><SettingRow title="Order updates" subtitle="Get notified when your order changes status"/><SettingRow title="Personalized experience" subtitle="Use your activity to improve recommendations"/><Text style={styles.muted}>Notification preferences are applied to future activity. Payment and security notices cannot be disabled.</Text></PageShell>;
 if(page==='about') return <PageShell title="ABOUT STAYUNKNOWN" onBack={()=>setPage('menu')}><View style={styles.about}><Text style={styles.aboutBrand}>STAYUNKNOWN</Text><Text style={styles.aboutText}>Move in silence. Stay unknown.</Text><Text style={styles.aboutText}>Independent streetwear from Lagos, built around limited drops and pieces made for people who don't need to be seen.</Text><Text style={styles.aboutMeta}>APP · STAYUNKNOWN 404</Text></View></PageShell>;
 return <ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>ACCOUNT</Text><Text style={styles.email}>{user.email}</Text>{admin?<Pressable style={styles.adminButton} onPress={onAdmin}><Text style={styles.adminText}>ADMIN DASHBOARD →</Text></Pressable>:null}<Text style={styles.section}>ACCOUNT</Text><MenuRow icon="◉" title="Profile" subtitle="Personal information" onPress={()=>setPage('profile')}/><MenuRow icon="▣" title="Orders" subtitle="Order history" onPress={onOrders}/><MenuRow icon="♡" title="Wishlist" subtitle="Saved products" onPress={onWishlist}/><MenuRow icon="♢" title="Notifications" subtitle="Activity and updates" onPress={onNotifications}/><MenuRow icon="◌" title="Support" subtitle="Support tickets and conversations" onPress={onSupport}/><MenuRow icon="⌖" title="Addresses" subtitle="Delivery addresses" onPress={()=>setPage('addresses')}/><MenuRow icon="⚙" title="Settings" subtitle="App and account settings" onPress={()=>setPage('settings')}/><MenuRow icon="i" title="About STAYUNKNOWN" subtitle="Brand information" onPress={()=>setPage('about')}/><Text style={styles.section}>SESSION</Text><Pressable style={styles.logout} onPress={()=>logout()}><Text style={styles.logoutText}>LOG OUT</Text></Pressable></ScrollView>;
}
function PageShell({title,onBack,children}:{title:string;onBack:()=>void;children:React.ReactNode}){return <ScrollView contentContainerStyle={styles.content}><Pressable onPress={onBack} style={styles.back}><Text style={styles.backText}>‹  BACK</Text></Pressable><Text style={styles.pageTitle}>{title}</Text><View style={styles.pageBody}>{children}</View></ScrollView>}
function MenuRow({icon,title,subtitle,onPress}:{icon:string;title:string;subtitle:string;onPress?:()=>void}){return <Pressable style={styles.menuRow} onPress={onPress}><View style={styles.iconBox}><Text style={styles.icon}>{icon}</Text></View><View style={styles.menuCopy}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuSubtitle}>{subtitle}</Text></View><Text style={styles.arrow}>›</Text></Pressable>}
function SettingRow({title,subtitle}:{title:string;subtitle:string}){return <View style={styles.settingRow}><View style={{flex:1}}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuSubtitle}>{subtitle}</Text></View><View style={styles.toggle}><View style={styles.toggleDot}/></View></View>}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:90},title:{color:'#fff',fontSize:38,fontWeight:'900',letterSpacing:1,marginBottom:8},pageTitle:{color:'#fff',fontSize:30,fontWeight:'900',letterSpacing:1,marginBottom:20},email:{color:'#777',fontSize:13,marginBottom:20},box:{borderWidth:1,borderColor:'#292929',padding:18,marginTop:10},pageBody:{paddingBottom:20},heading:{color:'#fff',fontSize:14,fontWeight:'900',letterSpacing:1,marginBottom:20},label:{color:'#888',fontSize:9,fontWeight:'900',letterSpacing:1,marginBottom:7},input:{backgroundColor:'#151515',borderWidth:1,borderColor:'#333',color:'#fff',padding:14,marginBottom:12},multiline:{minHeight:105,textAlignVertical:'top'},readonly:{backgroundColor:'#0d0d0d',borderWidth:1,borderColor:'#242424',padding:14,marginBottom:18},readonlyText:{color:'#777',fontSize:13},white:{backgroundColor:'#fff',paddingVertical:17,alignItems:'center',marginTop:4},black:{color:'#000',fontSize:10,fontWeight:'900',letterSpacing:1},switch:{color:'#aaa',fontSize:10,fontWeight:'900',letterSpacing:1,textAlign:'center',padding:18},outline:{borderWidth:1,borderColor:'#fff',paddingVertical:16,alignItems:'center',marginTop:10},outlineText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},adminButton:{backgroundColor:'#fff',paddingVertical:16,alignItems:'center',marginBottom:12},adminText:{color:'#000',fontSize:11,fontWeight:'900',letterSpacing:1},section:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:1,marginTop:25,marginBottom:8},menuRow:{minHeight:70,borderTopWidth:1,borderTopColor:'#222',flexDirection:'row',alignItems:'center',paddingVertical:10},iconBox:{width:38,height:38,borderWidth:1,borderColor:'#333',alignItems:'center',justifyContent:'center',marginRight:12},icon:{color:'#fff',fontSize:17},menuCopy:{flex:1},menuTitle:{color:'#fff',fontSize:13,fontWeight:'900'},menuSubtitle:{color:'#666',fontSize:10,marginTop:4,lineHeight:15},arrow:{color:'#777',fontSize:25,paddingLeft:10},back:{paddingVertical:8,marginBottom:10},backText:{color:'#aaa',fontSize:11,fontWeight:'900',letterSpacing:1},logout:{borderWidth:1,borderColor:'#333',paddingVertical:17,alignItems:'center'},logoutText:{color:'#aaa',fontSize:10,fontWeight:'900',letterSpacing:1},muted:{color:'#666',fontSize:11,lineHeight:18,marginTop:18},settingRow:{minHeight:70,borderTopWidth:1,borderTopColor:'#222',flexDirection:'row',alignItems:'center',paddingVertical:10},toggle:{width:42,height:24,borderRadius:12,backgroundColor:'#fff',justifyContent:'center',paddingHorizontal:3},toggleDot:{width:18,height:18,borderRadius:9,backgroundColor:'#000'},about:{borderWidth:1,borderColor:'#292929',padding:22},aboutBrand:{color:'#fff',fontSize:28,fontWeight:'900',letterSpacing:3},aboutText:{color:'#999',fontSize:13,lineHeight:21,marginTop:14},aboutMeta:{color:'#555',fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:28},message:{color:'#aaa',fontSize:11,marginBottom:12}});
