import React, { useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable, Image } from 'react-native';
import { getCart, getCartTotal, getCartCount, updateCartQuantity, removeFromCart } from '../services/store';

type Props={onBack:()=>void;onCheckout:()=>void};
export default function Bag({onBack,onCheckout}:Props){
 const [,refresh]=useState(0); const cart=getCart(); const total=getCartTotal(); const bump=()=>refresh(v=>v+1);
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>← BACK</Text></Pressable><Text style={styles.title}>404 BAG · {getCartCount()}</Text><View style={{width:45}}/></View>
  {cart.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>YOUR BAG IS EMPTY</Text><Text style={styles.emptyText}>Discover the latest STAYUNKNOWN pieces.</Text><Pressable style={styles.white} onPress={onBack}><Text style={styles.black}>CONTINUE SHOPPING</Text></Pressable></View>:<>
   {cart.map(item=><View key={`${item.product.id}-${item.size}-${item.color}`} style={styles.item}>
    <View style={styles.image}>{item.product.image?<Image source={{uri:item.product.image}} style={styles.imageActual}/>:<Text style={styles.placeholder}>STAYUNKNOWN</Text>}</View>
    <View style={styles.info}><Text style={styles.name}>{item.product.name}</Text><Text style={styles.price}>₦{Number(item.product.price).toLocaleString('en-NG')}</Text><Text style={styles.meta}>{item.color} · {item.size}</Text>
     <View style={styles.qty}><Pressable style={styles.qtyBtn} onPress={()=>{updateCartQuantity(item.product.id,item.size,item.color,item.quantity-1);bump();}}><Text style={styles.qtyText}>−</Text></Pressable><Text style={styles.qtyNumber}>{item.quantity}</Text><Pressable style={styles.qtyBtn} onPress={()=>{updateCartQuantity(item.product.id,item.size,item.color,item.quantity+1);bump();}}><Text style={styles.qtyText}>+</Text></Pressable></View>
     <Pressable onPress={()=>{removeFromCart(item.product.id,item.size,item.color);bump();}}><Text style={styles.remove}>REMOVE</Text></Pressable>
    </View>
   </View>)}
   <View style={styles.summary}><View style={styles.row}><Text style={styles.summaryLabel}>SUBTOTAL</Text><Text style={styles.summaryValue}>₦{total.toLocaleString('en-NG')}</Text></View><Text style={styles.shipping}>Shipping and final payment details are calculated at checkout.</Text><Pressable style={styles.checkout} onPress={onCheckout}><Text style={styles.checkoutText}>CHECKOUT →</Text></Pressable></View>
  </>}
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#000'},content:{paddingBottom:60},header:{height:70,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:'#fff',fontSize:15,fontWeight:'900',letterSpacing:1},empty:{minHeight:520,justifyContent:'center',alignItems:'center',padding:25},emptyTitle:{color:'#fff',fontSize:22,fontWeight:'900',letterSpacing:1,textAlign:'center'},emptyText:{color:'#777',fontSize:14,textAlign:'center',marginTop:10,marginBottom:25},white:{backgroundColor:'#fff',paddingVertical:16,paddingHorizontal:20},black:{color:'#000',fontSize:10,fontWeight:'900',letterSpacing:1},item:{padding:16,flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#1d1d1d'},image:{width:125,height:155,backgroundColor:'#151515',alignItems:'center',justifyContent:'center'},imageActual:{width:'100%',height:'100%'},placeholder:{color:'#555',fontSize:8,fontWeight:'900'},info:{flex:1,paddingLeft:15},name:{color:'#fff',fontSize:14,fontWeight:'900'},price:{color:'#aaa',fontSize:13,marginTop:5},meta:{color:'#666',fontSize:11,marginTop:7},qty:{flexDirection:'row',alignItems:'center',marginTop:15},qtyBtn:{width:30,height:30,borderWidth:1,borderColor:'#333',alignItems:'center',justifyContent:'center'},qtyText:{color:'#fff',fontSize:18},qtyNumber:{color:'#fff',width:35,textAlign:'center'},remove:{color:'#666',fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:12},summary:{padding:20,paddingTop:30},row:{flexDirection:'row',justifyContent:'space-between'},summaryLabel:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:1},summaryValue:{color:'#fff',fontSize:15,fontWeight:'900'},shipping:{color:'#666',fontSize:12,lineHeight:18,marginTop:10},checkout:{backgroundColor:'#fff',paddingVertical:17,alignItems:'center',marginTop:25},checkoutText:{color:'#000',fontSize:11,fontWeight:'900',letterSpacing:1}}
);
