import React, { useEffect, useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable, TextInput, Alert, Linking, ActivityIndicator } from 'react-native';
import { auth } from '../services/firebase';
import { clearCart, getCart, getCartTotal } from '../services/store';
import { initializePayment, verifyPayment, validatePromo, getProfile, saveProfile } from '../services/api';

type Props={onBack:()=>void;onComplete:()=>void};
export default function Checkout({onBack,onComplete}:Props){
 const cart=getCart(); const [email,setEmail]=useState(auth.currentUser?.email||''); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [address,setAddress]=useState(''); const [note,setNote]=useState(''); const [promo,setPromo]=useState(''); const [promoMessage,setPromoMessage]=useState(''); const [discount,setDiscount]=useState(0); const [loading,setLoading]=useState(false); const [status,setStatus]=useState('');
 const subtotal=getCartTotal(); const total=Math.max(0,subtotal-discount);
 useEffect(()=>{if(auth.currentUser) void getProfile().then(p=>{setPhone(p.phone);setAddress(p.address);}).catch(()=>{});},[]);
 useEffect(()=>{const handler=(event:{url:string})=>{const url=event.url;const match=url.match(/[?&](?:reference|trxref)=([^&]+)/i);if(match)void finishPayment(decodeURIComponent(match[1]));};const sub=Linking.addEventListener('url',handler);void Linking.getInitialURL().then(url=>{if(url){const match=url.match(/[?&](?:reference|trxref)=([^&]+)/i);if(match)void finishPayment(decodeURIComponent(match[1]));}});return()=>sub.remove();},[]);
 async function finishPayment(reference:string){try{setStatus('VERIFYING PAYMENT…');const result=await verifyPayment(reference);if(result.paid){clearCart();setStatus('PAYMENT CONFIRMED');Alert.alert('Order confirmed','Your STAYUNKNOWN order has been received.',[{text:'DONE',onPress:onComplete}]);}else{setStatus(`Payment status: ${result.status}`);}}catch(e:any){setStatus(e?.message||'Unable to verify payment.');}}
 async function applyPromo(){if(!promo.trim()){setDiscount(0);setPromoMessage('');return;}try{setLoading(true);const result=await validatePromo(promo.trim(),cart.map(i=>({id:i.product.id,price:i.product.price,quantity:i.quantity,collection:i.product.collection,category:i.product.category})));if(result.valid){setDiscount(Number(result.discount||0));setPromoMessage(`PROMO APPLIED — ₦${Number(result.discount||0).toLocaleString('en-NG')} OFF`);}else{setDiscount(0);setPromoMessage(result.error||'Invalid promo code.');}}catch(e:any){setDiscount(0);setPromoMessage(e?.message||'Invalid promo code.');}finally{setLoading(false);}}
 async function pay(){if(!cart.length)return Alert.alert('Your bag is empty');if(!email.includes('@')||!name.trim()||!address.trim()){Alert.alert('Missing checkout details','Enter your name, email and delivery address.');return;}try{setLoading(true);setStatus('PREPARING PAYMENT…');if(auth.currentUser)await saveProfile({phone,address});const callbackUrl='stayunknown://payment-complete';const result=await initializePayment({email:email.trim(),phone:phone.trim(),name:name.trim(),address:address.trim(),note:note.trim(),promoCode:promo.trim()||undefined,userId:auth.currentUser?.uid||'',callbackUrl,items:cart.map(i=>({productId:i.product.id,quantity:i.quantity,size:i.size,color:i.color}))});setStatus('OPENING PAYSTACK…');await Linking.openURL(result.authorization_url);}catch(e:any){setStatus(e?.message||'Unable to start payment.');}finally{setLoading(false);}}
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>← BAG</Text></Pressable><Text style={styles.title}>CHECKOUT</Text><View style={{width:45}}/></View><Text style={styles.heading}>DELIVERY DETAILS</Text><Field label="NAME" value={name} onChangeText={setName} placeholder="Full name"/><Field label="EMAIL" value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address"/><Field label="PHONE" value={phone} onChangeText={setPhone} placeholder="Phone number" keyboardType="phone-pad"/><Field label="ADDRESS" value={address} onChangeText={setAddress} placeholder="Delivery address" multiline/><Field label="ORDER NOTE" value={note} onChangeText={setNote} placeholder="Optional note" multiline/>
 <Text style={styles.heading}>PROMO</Text><View style={styles.promoRow}><TextInput style={styles.promoInput} value={promo} onChangeText={setPromo} placeholder="CODE" placeholderTextColor="#555" autoCapitalize="characters"/><Pressable style={styles.promoButton} onPress={applyPromo} disabled={loading}><Text style={styles.promoText}>APPLY</Text></Pressable></View>{promoMessage?<Text style={styles.message}>{promoMessage}</Text>:null}
 <View style={styles.summary}><View style={styles.row}><Text style={styles.label}>SUBTOTAL</Text><Text style={styles.value}>₦{subtotal.toLocaleString('en-NG')}</Text></View><View style={styles.row}><Text style={styles.label}>DISCOUNT</Text><Text style={styles.value}>− ₦{discount.toLocaleString('en-NG')}</Text></View><View style={[styles.row,styles.totalRow]}><Text style={styles.totalLabel}>TOTAL</Text><Text style={styles.totalValue}>₦{total.toLocaleString('en-NG')}</Text></View></View>
 {status?<Text style={styles.status}>{status}</Text>:null}<Pressable style={styles.pay} onPress={pay} disabled={loading}>{loading?<ActivityIndicator color="#000"/>:<Text style={styles.payText}>PAY WITH PAYSTACK →</Text>}</Pressable><Text style={styles.security}>Payment is processed securely by Paystack. Your card/payment details are not stored by this app.</Text></ScrollView></SafeAreaView>
}
function Field({label,value,onChangeText,placeholder,multiline=false,keyboardType='default'}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;multiline?:boolean;keyboardType?:any}){return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput style={[styles.input,multiline&&styles.multiline]} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#555" multiline={multiline} keyboardType={keyboardType}/></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#000'},content:{padding:20,paddingBottom:60},header:{height:55,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:'#fff',fontSize:10,fontWeight:'900'},title:{color:'#fff',fontSize:15,fontWeight:'900',letterSpacing:1},heading:{color:'#fff',fontSize:13,fontWeight:'900',letterSpacing:1,marginTop:25,marginBottom:15},field:{marginBottom:14},fieldLabel:{color:'#888',fontSize:9,fontWeight:'900',letterSpacing:1,marginBottom:7},input:{backgroundColor:'#151515',borderWidth:1,borderColor:'#333',color:'#fff',padding:14,fontSize:14},multiline:{minHeight:90,textAlignVertical:'top'},promoRow:{flexDirection:'row',gap:8},promoInput:{flex:1,backgroundColor:'#151515',borderWidth:1,borderColor:'#333',color:'#fff',padding:14},promoButton:{backgroundColor:'#fff',paddingHorizontal:18,justifyContent:'center'},promoText:{color:'#000',fontSize:10,fontWeight:'900'},message:{color:'#aaa',fontSize:11,marginTop:8},summary:{marginTop:30,borderTopWidth:1,borderTopColor:'#222',paddingTop:20},row:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},label:{color:'#888',fontSize:10,fontWeight:'800'},value:{color:'#fff',fontSize:12,fontWeight:'800'},totalRow:{marginTop:8,paddingTop:16,borderTopWidth:1,borderTopColor:'#222'},totalLabel:{color:'#fff',fontSize:13,fontWeight:'900'},totalValue:{color:'#fff',fontSize:18,fontWeight:'900'},status:{color:'#aaa',fontSize:11,marginTop:20},pay:{backgroundColor:'#fff',paddingVertical:18,alignItems:'center',marginTop:22},payText:{color:'#000',fontSize:11,fontWeight:'900',letterSpacing:1},security:{color:'#555',fontSize:10,lineHeight:16,textAlign:'center',marginTop:14}}
);
