import React, { useEffect, useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable, Image, ActivityIndicator } from 'react-native';
import { Collection, getCatalog, getCollections, Product } from '../services/api';

type Props={onBack:()=>void;onProduct:(product:Product)=>void};
export default function Collections({onBack,onProduct}:Props){
 const [collections,setCollections]=useState<Collection[]>([]);const [products,setProducts]=useState<Product[]>([]);const [selected,setSelected]=useState<Collection|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{void load();},[]);async function load(){try{setLoading(true);const [c,p]=await Promise.all([getCollections(),getCatalog()]);setCollections(c);setProducts(p);}catch(e:any){setError(e?.message||'Unable to load collections.');}finally{setLoading(false);}}
 const selectedProducts=useMemo(()=>{if(!selected)return[];const ids=new Set((selected.productIds||[]).map(String));const byId=products.filter(p=>ids.has(p.id));if(byId.length)return byId;return products.filter(p=>String(p.collection||'').trim().toLowerCase()===selected.name.trim().toLowerCase());},[selected,products]);
 if(loading)return <SafeAreaView style={styles.container}><View style={styles.center}><ActivityIndicator color="#fff"/><Text style={styles.muted}>LOADING COLLECTIONS…</Text></View></SafeAreaView>;
 if(selected)return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>setSelected(null)}><Text style={styles.back}>← ALL COLLECTIONS</Text></Pressable></View><Text style={styles.title}>{selected.name}</Text>{selected.description?<Text style={styles.description}>{selected.description}</Text>:null}<View style={styles.hero}>{selected.image?<Image source={{uri:selected.image}} style={styles.heroImage}/>:<Text style={styles.heroText}>{selected.name}</Text>}</View><Text style={styles.count}>{selectedProducts.length} {selectedProducts.length===1?'PIECE':'PIECES'}</Text>{selectedProducts.length===0?<Text style={styles.muted}>No products are assigned to this collection yet.</Text>:<View style={styles.grid}>{selectedProducts.filter(p=>!p.hidden).map(p=><Pressable key={p.id} style={styles.product} onPress={()=>onProduct(p)}><View style={styles.productImage}>{p.image?<Image source={{uri:p.image}} style={styles.image}/>:<Text style={styles.placeholder}>STAYUNKNOWN</Text>}</View><Text style={styles.name}>{p.name}</Text><Text style={styles.price}>₦{Number(p.price).toLocaleString('en-NG')}</Text></Pressable>)}</View>}</ScrollView></SafeAreaView>;
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>← BACK</Text></Pressable></View><Text style={styles.title}>COLLECTIONS</Text>{error?<View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable style={styles.outline} onPress={load}><Text style={styles.outlineText}>TRY AGAIN</Text></Pressable></View>:collections.length===0?<View style={styles.center}><Text style={styles.muted}>NO COLLECTIONS YET.</Text></View>:<View style={styles.list}>{collections.map(c=><Pressable key={c.id} style={styles.card} onPress={()=>setSelected(c)}><View style={styles.cardImage}>{c.image?<Image source={{uri:c.image}} style={styles.image}/>:<Text style={styles.cardName}>{c.name}</Text>}</View><View style={styles.cardBottom}><Text style={styles.cardName}>{c.name}</Text><Text style={styles.arrow}>→</Text></View><Text style={styles.count}>{c.productCount||0} {(c.productCount||0)===1?'PIECE':'PIECES'}</Text></Pressable>)}</View>}</ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#000'},content:{padding:20,paddingBottom:60},header:{height:55,justifyContent:'center'},back:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:'#fff',fontSize:38,fontWeight:'900',letterSpacing:1,marginBottom:20},description:{color:'#888',fontSize:14,lineHeight:21,marginBottom:20},list:{gap:16},card:{borderWidth:1,borderColor:'#2b2b2b',paddingBottom:16},cardImage:{height:280,backgroundColor:'#111',alignItems:'center',justifyContent:'center'},image:{width:'100%',height:'100%'},cardBottom:{paddingHorizontal:16,paddingTop:14,flexDirection:'row',justifyContent:'space-between'},cardName:{color:'#fff',fontSize:18,fontWeight:'900',letterSpacing:1},arrow:{color:'#fff',fontSize:20},count:{color:'#777',fontSize:10,fontWeight:'800',letterSpacing:1,paddingHorizontal:16,marginTop:7},hero:{height:340,backgroundColor:'#111',alignItems:'center',justifyContent:'center'},heroImage:{width:'100%',height:'100%'},heroText:{color:'#fff',fontSize:32,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',marginHorizontal:-6},product:{width:'50%',padding:6,marginBottom:18},productImage:{height:230,backgroundColor:'#151515',alignItems:'center',justifyContent:'center'},name:{color:'#fff',fontSize:12,fontWeight:'800',marginTop:8},price:{color:'#888',fontSize:12,marginTop:4},placeholder:{color:'#555',fontSize:9,fontWeight:'900'},center:{minHeight:400,justifyContent:'center',alignItems:'center',gap:12},muted:{color:'#777',fontSize:11,fontWeight:'800',letterSpacing:1,textAlign:'center'},error:{color:'#fff',textAlign:'center'},outline:{borderWidth:1,borderColor:'#fff',paddingHorizontal:20,paddingVertical:14},outlineText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:1}}
);
