import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getOrderHistory, getOrder, Order } from '../services/api';

const STATUSES = ['ALL','PENDING','PAID','PROCESSING','PACKED','SHIPPED','DELIVERED','FAILED'];

type Props = { initialOrderId?: string };

export default function Orders({ initialOrderId }: Props){
  const [orders,setOrders]=useState<Order[]>([]); const [query,setQuery]=useState(''); const [status,setStatus]=useState('ALL');
  const [selected,setSelected]=useState<Order|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{try{setLoading(true);setError('');setOrders(await getOrderHistory());}catch(e:any){setError(e?.message||'Unable to load orders.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(initialOrderId && orders.length){const match=orders.find(o=>String(o.id)===String(initialOrderId));if(match)void open(match);}},[initialOrderId,orders.length]);
  const filtered=useMemo(()=>orders.filter(o=>{const text=JSON.stringify(o).toLowerCase();const matches=!query.trim()||text.includes(query.trim().toLowerCase());const s=String(o.deliveryStatus||o.status||o.paymentStatus||'PENDING').toUpperCase();return matches&&(status==='ALL'||s===status);}),[orders,query,status]);
  async function open(o:Order){try{setSelected(await getOrder(o.id));}catch{setSelected(o);}}
  if(selected)return <OrderDetails order={selected} onBack={()=>setSelected(null)}/>;
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><Text style={styles.title}>ORDERS</Text><Pressable onPress={load}><Text style={styles.refresh}>REFRESH</Text></Pressable></View>
    <TextInput value={query} onChangeText={setQuery} placeholder="SEARCH ORDER, PRODUCT, EMAIL..." placeholderTextColor="#555" style={styles.input} autoCapitalize="none"/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{STATUSES.map(s=><Pressable key={s} onPress={()=>setStatus(s)} style={[styles.filter,status===s&&styles.filterActive]}><Text style={[styles.filterText,status===s&&styles.filterTextActive]}>{s}</Text></Pressable>)}</ScrollView>
    {loading?<ActivityIndicator color="#fff"/>:error?<Text style={styles.muted}>{error}</Text>:filtered.length===0?<Text style={styles.muted}>NO ORDERS FOUND.</Text>:filtered.map(o=>{const s=String(o.deliveryStatus||o.status||o.paymentStatus||'PENDING').toUpperCase();return <Pressable key={o.id} style={styles.card} onPress={()=>open(o)}><View style={styles.row}><Text style={styles.order}>{o.orderNumber||o.id}</Text><Text style={styles.status}>{s}</Text></View><Text style={styles.meta}>{o.name||o.customer?.name||o.email||o.customer?.email||'CUSTOMER'}</Text><Text style={styles.meta}>{Array.isArray(o.items)?`${o.items.length} item${o.items.length===1?'':'s'} · `:''}₦{Number(o.total||o.amount||0).toLocaleString('en-NG')}</Text><Text style={styles.open}>VIEW ORDER →</Text></Pressable>})}
  </ScrollView></SafeAreaView>
}

function OrderDetails({order,onBack}:{order:Order;onBack:()=>void}){const s=String(order.deliveryStatus||order.status||order.paymentStatus||'PENDING').toUpperCase();const steps=['PAID','PROCESSING','PACKED','SHIPPED','DELIVERED'];const current=Math.max(0,steps.indexOf(s));return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}>
  <Pressable onPress={onBack}><Text style={styles.back}>←</Text></Pressable><Text style={styles.big}>{order.orderNumber||order.id}</Text><Text style={styles.meta}>{order.email||order.customer?.email||''}</Text>
  <View style={styles.timeline}>{steps.map((x,i)=><View key={x} style={styles.step}><View style={[styles.dot,i<=current&&styles.dotActive]}/><View><Text style={[styles.stepTitle,i<=current&&styles.activeText]}>{x}</Text>{i===current?<Text style={styles.current}>CURRENT STATUS</Text>:null}</View></View>)}</View>
  <Text style={styles.section}>ITEMS</Text>{(order.items||[]).map((i:any,n:number)=><View key={n} style={styles.item}><Text style={styles.itemName}>{i.name||i.productName||i.productId}</Text><Text style={styles.meta}>Qty {i.quantity||1} · {i.size||''} · {i.color||''}</Text></View>)}
  <Text style={styles.section}>DELIVERY</Text><View style={styles.card}><Text style={styles.meta}>Courier</Text><Text style={styles.value}>{order.courier||'Not assigned'}</Text><Text style={styles.meta}>Tracking</Text>{(order.trackingNumber||order.tracking||order.trackingUrl)?<Pressable onPress={()=>{const target=String(order.trackingUrl||order.trackingNumber||order.tracking||''); if(/^https?:\/\//i.test(target)) void Linking.openURL(target);}}><Text style={styles.link}>{order.trackingNumber||order.tracking||order.trackingUrl}</Text></Pressable>:<Text style={styles.value}>Not available yet</Text>}<Text style={styles.meta}>Estimated delivery</Text><Text style={styles.value}>{order.estimatedDelivery||'—'}</Text><Text style={styles.meta}>Note</Text><Text style={styles.value}>{order.deliveryNote||order.deliveryNotes||order.note||'—'}</Text></View>
  <Text style={styles.section}>TOTAL</Text><Text style={styles.total}>₦{Number(order.total||order.amount||0).toLocaleString('en-NG')}</Text>
 </ScrollView></SafeAreaView>}

const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#000'},content:{padding:18,paddingBottom:80},header:{height:55,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:'#fff',fontSize:26,fontWeight:'900',letterSpacing:1},refresh:{color:'#aaa',fontSize:9,fontWeight:'900'},input:{backgroundColor:'#151515',borderWidth:1,borderColor:'#333',color:'#fff',padding:14,marginBottom:12},filters:{gap:7,paddingBottom:16},filter:{borderWidth:1,borderColor:'#333',paddingHorizontal:11,paddingVertical:9},filterActive:{backgroundColor:'#fff',borderColor:'#fff'},filterText:{color:'#777',fontSize:8,fontWeight:'900'},filterTextActive:{color:'#000'},card:{borderWidth:1,borderColor:'#292929',padding:15,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',gap:10},order:{color:'#fff',fontSize:12,fontWeight:'900'},status:{color:'#fff',fontSize:8,fontWeight:'900',borderWidth:1,borderColor:'#444',paddingHorizontal:7,paddingVertical:5},meta:{color:'#777',fontSize:10,lineHeight:17,marginTop:4},open:{color:'#fff',fontSize:9,fontWeight:'900',marginTop:12},muted:{color:'#666',fontSize:11,lineHeight:18},back:{color:'#fff',fontSize:26,fontWeight:'400',lineHeight:30,width:42},big:{color:'#fff',fontSize:27,fontWeight:'900',marginTop:20},timeline:{marginTop:28,borderLeftWidth:1,borderLeftColor:'#333',paddingLeft:18},step:{flexDirection:'row',gap:13,marginBottom:20,marginLeft:-24},dot:{width:10,height:10,borderRadius:5,borderWidth:1,borderColor:'#555',backgroundColor:'#000'},dotActive:{backgroundColor:'#fff',borderColor:'#fff'},stepTitle:{color:'#555',fontSize:10,fontWeight:'900'},activeText:{color:'#fff'},current:{color:'#777',fontSize:8,marginTop:3},section:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:1,marginTop:28,marginBottom:12},item:{borderTopWidth:1,borderTopColor:'#222',paddingVertical:12},itemName:{color:'#fff',fontSize:11,fontWeight:'900'},value:{color:'#fff',fontSize:12,marginTop:4},link:{color:'#aaa',fontSize:11,marginTop:4},total:{color:'#fff',fontSize:24,fontWeight:'900'}});
